---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbittorrent
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: qbittorrent
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name": "vpn",
                "namespace": "kube-system",
                "mac": "f2:f9:00:00:90:06",
                "ips": ["10.10.90.10/24"]
              }]
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.2.4@sha256:9307627e03981d5473aa31175ea76ed56ea3752333ca49d601b6af45e281e7ba
            env:
              UMASK: "022"
              QBT_WEBUI_PORT: &port 80
              QBT_TORRENTING_PORT: &torrentPort 51413
              #PUSHOVER_ENABLED: true
              TZ: Europe/London
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: [ALL] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi
          vuetorrent:
            dependsOn: app
            image:
              repository: registry.k8s.io/git-sync/git-sync
              tag: v4.7.0
            args:
              - --repo=https://github.com/WDaan/VueTorrent
              - --ref=latest-release
              - --period=86400s
              - --init-period=10s
              - --init-max-failures=-1
              - --root=/addons
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 32Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        primary: true
        forceRename: *app
        ports:
          http:
            primary: true
            port: *port
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == any(200,401)"]
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads Service
          gethomepage.dev/name: QBittorrent
          gethomepage.dev/description: Torrent Downloader
          gethomepage.dev/icon: qbittorrent
          gethomepage.dev/widget.type: qbittorrent
          gethomepage.dev/widget.url: http://qbittorrent.default
        hostnames:
          - "torrents.f9.casa"
        parentRefs:
          - name: envoy-external
            namespace: network
        rules:
          - backendRefs:
              - name: *app
                port: *port
    configMaps:
      config:
        data:
          .qbt.toml: |
            [qbittorrent]
            addr = "http://localhost:80"

    persistence:
      config:
        existingClaim: *app
        advancedMounts:
          *app :
            app:
              - path: /config
      config-file:
        type: configMap
        name: *app
        advancedMounts:
          *app : # in qbit config, set "on torrent add" to "/config/qbrr --hash "%I" && qbt tag delete "cross-seed""
            app:
              - path: /config/.qbt.toml
                subPath: .qbt.toml
                readOnly: true

      tmpfs:
        type: emptyDir
        advancedMounts:
          *app :
            app:
              - path: /addons
                subPath: addons
            vuetorrent:
              - path: /addons
                subPath: addons

      media:
        type: nfs
        server: nas.main.internal
        path: /mnt/F9/Media/Downloads
        globalMounts:
          - path: /downloads
