---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app music-assistant
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: music-assistant
  values:
    controllers:
      music-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"media",
                "namespace": "kube-system",
                "mac": "f2:f9:00:00:40:04",
                "ips": ["10.10.40.241/24"]
              }]
        containers:
          app:
            image:
              repository: ghcr.io/music-assistant/server
              tag: 2.8.6@sha256:400697b305e45bd1712c019e67d22681219e91deb41afe88939f921b5fae137f
            env:
              TZ: ${TIMEZONE}
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 2048Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
                add:
                  - SYS_ADMIN
                  - DAC_READ_SEARCH

          bgutil-provider:
            image:
              repository: docker.io/brainicism/bgutil-ytdlp-pot-provider
              tag: 1.3.1
            env:
              TZ: ${TIMEZONE}
              PORT: 4416
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.10.69.205
        controller: *app
        ports:
          http:
            port: &port 8095
            primary: true
          stream:
            port: 8097
          connect1:
            port: 32500
          connect2:
            port: 32501
          gdm1:
            port: 32410
            protocol: UDP
          gdm2:
            port: 32412
            protocol: UDP
          gdm3:
            port: 32413
            protocol: UDP
          gdm4:
            port: 32414
            protocol: UDP
          gdm5:
            port: 32500
            protocol: UDP
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == any(200,401)"]
        hostnames:
          - music.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-external
            namespace: network
            
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
      media:
        type: nfs
        server: nas.main.internal
        path: /mnt/F9/Media/Music
        globalMounts:
          - path: /music
      tmpfs:
        type: emptyDir
        sizeLimit: 2Gi
        globalMounts:
          - path: /.audio
            subPath: .audio
          - path: /.cache
            subPath: .cache
          - path: /tmp
            subPath: tmp
