services:
  # Scanner's physical Scan button: scans the feeder (duplex) into a PDF in the
  # Paperless consumption dir.
  scanbutton:
    build:
      context: .
    container_name: "scanbutton"
    entrypoint: ["/opt/brother/scanner/brscan-skey/brscan-skey", "-f"]
    environment:
      TZ: "Europe/London"
    privileged: true
    restart: "unless-stopped"
    tty: true
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
      - "/mnt/F9/Documents/incoming:/output"
