---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mosquitto
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mosquitto-secret
    template:
      data:
        MQTT_USERNAME: "{{ .MQTT_USERNAME }}"
        MQTT_PASSWORD: "{{ .MQTT_PASSWORD }}"
  dataFrom:
    - extract:
        key: mosquitto
