---
name: immich-machine-learning
working_dir: docker/ai/immich-machine-learning
# ---
# name: stable-diffusion
# working_dir: docker/ai/stable-diffusion
---
name: whisper
working_dir: docker/ai/whisper
---
name: llamacpp
working_dir: docker/ai/llamacpp
---
name: webtop
working_dir: docker/management/webtop
---
name: isponsorblocktv
working_dir: docker/media/isponsorblocktv
---
name: tdarr
working_dir: docker/media/tdarr
---
name: node-exporter
working_dir: docker/observability/node-exporter
---
name: smartctl-exporter
working_dir: docker/observability/smartctl-exporter
---
name: liquidctl-exporter
working_dir: docker/observability/liquidctl-exporter
---
name: cups
working_dir: docker/system/cups
---
name: pbs
working_dir: docker/system/pbs
---
name: backup
working_dir: docker/backup/garage
---
name: frigate
working_dir: docker/security/frigate
external_secrets:
  FRIGATE_REOLINK_HOST: op://kubernetes/frigate/REOLINK_HOST
  FRIGATE_REOLINK_USER: op://kubernetes/frigate/REOLINK_USERNAME
  FRIGATE_REOLINK_PASSWORD: op://kubernetes/frigate/REOLINK_PASSWORD
  FRIGATE_DOORBELL_HOST: op://kubernetes/frigate/DOORBELL_HOST
  FRIGATE_DOORBELL_USER: op://kubernetes/frigate/DOORBELL_USERNAME
  FRIGATE_DOORBELL_PASSWORD: op://kubernetes/frigate/DOORBELL_PASSWORD
  FRIGATE_OPENWEBUI_API_KEY: op://kubernetes/frigate/OPENWEBUI_API_KEY
  FRIGATE_RTSP_USERNAME: op://kubernetes/frigate/RTSP_USERNAME
  FRIGATE_RTSP_PASSWORD: op://kubernetes/frigate/RTSP_PASSWORD
  FRIGATE_GARAGE_HOST: op://kubernetes/frigate/GARAGE_HOST
  FRIGATE_GARAGE_USER: op://kubernetes/frigate/GARAGE_USERNAME
  FRIGATE_GARAGE_PASSWORD: op://kubernetes/frigate/GARAGE_PASSWORD
  FRIGATE_MQTT_USERNAME: op://kubernetes/mosquitto/MQTT_USERNAME
  FRIGATE_MQTT_PASSWORD: op://kubernetes/mosquitto/MQTT_PASSWORD
