---
- System:
    - Unifi:
        icon: unifi.png
        href: "https://unifi.ui.com"
        description: Unifi Gateway
        siteMonitor: https://unifi.internal
        widget:
          type: unifi
          url: https://unifi.internal
          key: { { HOMEPAGE_VAR_UNIFI_KEY } }

- Infrastructure:
    - TrueNAS:
        icon: truenas-scale
        href: https://truenas.f9.casa
        description: NAS
        siteMonitor: http://nas.main.internal
    - Webtop:
        icon: mdi-desktop-classic
        href: https://remote.f9.casa
        description: Remote desktop
        siteMonitor: http://nas.main.internal:3000
    - NanoKVM:
        icon: mdi-remote-desktop
        href: https://kvm.f9.casa
        description: Network KVM
        siteMonitor: http://kvm.not.internal
    - Garage:
        icon: garage
        href: https://garage.f9.casa
        description: S3 storage admin
        siteMonitor: http://nas.main.internal:3909
    - Tdarr:
        icon: tdarr
        href: https://tdarr.f9.casa
        description: Media transcoding
        siteMonitor: http://nas.main.internal:8265
    - Frigate:
        icon: frigate
        href: https://frigate.f9.casa
        description: NVR / cameras
        siteMonitor: http://nas.main.internal:8971

- Calendar:
    - Calendar:
        name:
        widget:
          type: calendar
          view: agenda # optional - possible values monthly, agenda
          maxEvents: 14 # optional - defaults to 10
          previousDays: 3
          showTime: true # optional - show time for event happening today - defaults to false
          timezone: Europe/London # optional and only when timezone is not detected properly (slightly slower performance) - force timezone for ical events (if it's the same - no change, if missing or different in ical - will be converted to this timezone)
          integrations: # optional
            - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr, ical
              service_group: Downloads Service # group name where widget exists
              service_name: Sonarr # service name for that widget
              color: teal # optional - defaults to pre-defined color for the service (teal for sonarr)
            - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr, ical
              service_group: Downloads Service # group name where widget exists
              service_name: Radarr # service name for that widget
              color: amber # optional - defaults to pre-defined color for the service (teal for sonarr)
