---
- System:
  - Unifi:
      icon: unifi.png
      href: "https://unifi.ui.com"
      description: Unifi Gateway
      siteMonitor: https://unifi.internal
      widget:
        type: unifi
        url: https://unifi.internal
        key: {{HOMEPAGE_VAR_UNIFI_KEY}}

# - Downloaders:
#   - qBittorrent:
#       icon: qbittorrent.png
#       href: "{{HOMEPAGE_VAR_QBITTORRENT_HREF}}"
#       description: Torrent Client
#       siteMonitor: "http://qbittorrent.default.svc.cluster.local"
#       widget:
#         type: qbittorrent
#         url: "http://qbittorrent.default.svc.cluster.local"
#         enableLeechProgress: true

  # - SABnzbd:
  #     icon: sabnzbd.png
  #     href: "{{HOMEPAGE_VAR_SABNZBD_HREF}}"
  #     description: Usenet Client
  #     siteMonitor: "http://sabnzbd.default.svc.cluster.local"
  #     widget:
  #       type: sabnzbd
  #       url: "http://sabnzbd.default.svc.cluster.local"
  #       key: "{{HOMEPAGE_VAR_SABNZBD_KEY}}"

# - Home Automation:
#   - Home Assistant:
#         custom:
#           - state: sensor.smart_electricity_meter_usage_today
#             label: Energy Usage Today
#           - state: sensor.smart_electricity_meter_cost_today
#             label: Energy Cost Today

  # - Frigate:
  #     icon: frigate.png
  #     href: "{{HOMEPAGE_VAR_FRIGATE_HREF}}"
  #     description: CCTV Management
  #     siteMonitor: "http://frigate.default.svc.cluster.local:5000"
  #     widget:
  #       type: frigate
  #       url: "http://frigate.default.svc.cluster.local:5000"
  #       enableRecentEvents: false

- Calendar:
    - Calendar:
        name:
        widget:
          type: calendar
          view: agenda # optional - possible values monthly, agenda
          maxEvents: 14 # optional - defaults to 10
          previousDays: 3
          showTime: true # optional - show time for event happening today - defaults to false
          timezone: Europe/London # optional and only when timezone is not detected properly (slightly slower performance) - force timezone for ical events (if it's the same - no change, if missing or different in ical - will be converted to this timezone)
          integrations: # optional
            - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr, ical
              service_group: Downloads Service # group name where widget exists
              service_name: Sonarr # service name for that widget
              color: teal # optional - defaults to pre-defined color for the service (teal for sonarr)
            - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr, ical
              service_group: Downloads Service # group name where widget exists
              service_name: Radarr # service name for that widget
              color: amber # optional - defaults to pre-defined color for the service (teal for sonarr)