---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${external.f9.casa//./-}
spec:
  dnsNames:
      - f9.casa
      - "*.f9.casa"
      - "*.s3.f9.casa"
  duration: 160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: f9-casa-tls
  usages:
    - digital signature
