---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grocy
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: grocy
  values:
    controllers:
      grocy:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          grocy:
            image:
              repository: ghcr.io/linuxserver/grocy
              tag: 4.6.0
            env:
              PUID: 1000
              PGID: 1000
              TZ: ${TIMEZONE}
              MAX_UPLOAD: 50M
              PHP_MAX_FILE_UPLOAD: 200
              PHP_MAX_POST: 100M
              PHP_MEMORY_LIMIT: 512M
              GROCY_MODE: production
              GROCY_REVERSE_PROXY_AUTH_HEADER: Remote-User
              GROCY_CULTURE: "en_GB"
              GROCY_CURRENCY: "GBP"
              GROCY_AUTH_CLASS: Grocy\Middleware\ReverseProxyAuthMiddleware
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      viewcache:
        type: emptyDir
        globalMounts:
          - path: /config/data/viewcache
    route:
      grocy:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == any(200,401)"]
        hostnames:
          - "grocy.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: network
        rules:
          - backendRefs:
              - port: 80
                name: grocy
    service:
      grocy:
        controller: grocy
        type: ClusterIP
        ports:
          http:
            primary: true
            port: 80