---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: searxng
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: searxng
  values:
    controllers:
      searxng:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/searxng/searxng
              tag: 2026.7.8-1412926f5@sha256:a87eb8a2b2b65243c431979938aec37d86534f278f44b8115970212a08c32f23
            env:
              TZ: Europe/London
              SEARXNG_BASE_URL: https://search.f9.casa
              SEARXNG_URL: https://search.f9.casa
              SEARXNG_PORT: &port 8080
              UWSGI_WORKERS: 1
              UWSGI_THREADS: 4
              SEARXNG_REDIS_URL: redis://dragonfly.database.svc.cluster.local:6379/12
            envFrom:
              - secretRef:
                  name: searxng-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *port
                  initialDelaySeconds: 15
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 977
        runAsGroup: 977
        fsGroup: 977
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        annotations:
          ggatus.home-operations.com/enabled: 'false'
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Home
          gethomepage.dev/name: SearXNG Search
          gethomepage.dev/icon: searxng.svg
          gethomepage.dev/pod-selector: app.kubernetes.io/name=searxng
        hostnames:
          - "search.f9.casa"
        parentRefs:
          - name: envoy-external
            namespace: network

    persistence:
      config:
        type: configMap
        name: searxng-configmap
        globalMounts:
          - path: /etc/searxng/settings.yml
            subPath: settings.yml
            readOnly: true
          - path: /etc/searxng/limiter.toml
            subPath: limiter.toml
            readOnly: true
      tmpfs:
        type: emptyDir
        advancedMounts:
          searxng:
            app:
              - path: /tmp
                subPath: tmp