---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mcp

components:
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./flux-operator-mcp/ks.yaml
  - ./grafana-mcp/ks.yaml
  - ./truenas-mcp/ks.yaml
  - ./unifi-network-mcp/ks.yaml
