---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mcp

components:
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./toolhive-crds/ks.yaml
  - ./toolhive-operator/ks.yaml
  - ./toolhive-servers/ks.yaml
