---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app overlays
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: overlays
  values:
    controllers:
      overlays:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/fma965/obs-overlays
              tag: v2.0.1
            envFrom:
              - secretRef:
                  name: overlays-secret
            securityContext:
              allowPrivilegeEscalation: false
              #   readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: 8080
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == any(200,401)"]
            url: "https://{{ .Release.Name }}.f9.casa/timer/index.html"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Web Projects
          gethomepage.dev/name: Overlays
          gethomepage.dev/icon: mdi-layers
        hostnames:
          - "{{ .Release.Name }}.f9.casa"
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
