---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./grafana-mcp
  - ./ha-mcp
  - ./truenas-mcp
  - ./unifi-network-mcp
  - ./kubernetes-mcp-server
  - ./flux-operator-mcp
  - ./victoria-logs-mcp
  - ./paperless-mcp
  - ./github-mcp
  - ./immich-mcp
