services:
  webtop:
    image: lscr.io/linuxserver/webtop:debian-xfce@sha256:31e682d7ca1c240c5bcf91ed2e9ed47ac7ae4e65e61718d5ad44c98489a4077b
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TITLE=F9 Remote
      - DRINODE=/dev/dri/renderD128
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - /mnt/apps-pool/appdata/webtop/config:/config
      - ./resources:/custom-cont-init.d:ro
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb" #optional
    restart: unless-stopped
