services:
  webtop:
    image: lscr.io/linuxserver/webtop:debian-xfce@sha256:ec0b8f221e554d4da51f9e074658c9778fc714a54737f297d3ba5cd87db495ad
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TITLE=F9 Remote
      - DRINODE=/dev/dri/renderD128
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - /mnt/apps-pool/appdata/webtop/config:/config
      - ./resources:/custom-cont-init.d:ro
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb" #optional
    restart: unless-stopped
