services:
  webtop:
    image: lscr.io/linuxserver/webtop:debian-xfce@sha256:a2f42b3e0b14becd717a2d63c471e52fb5ee2c3be5daa6bafbdda0f8f47a232a
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TITLE=F9 Remote
      - DRINODE=/dev/dri/renderD128
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - /mnt/apps-pool/appdata/webtop/config:/config
      - ./resources:/custom-cont-init.d:ro
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb" #optional
    restart: unless-stopped
