services:
  llamacpp:
    container_name: llamacpp
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
        # limits:
        #   memory: 4G
    environment:
      TZ: "Europe/London"
      DISABLED_OLLAMA_KEEP_ALIVE: "15m"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      NVIDIA_VISIBLE_DEVICES: "all"
    ports:
      - 8080:8080
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    volumes:
      - /mnt/AI/appdata/llamacpp/models:/models:ro
      - /mnt/AI/appdata/llamacpp/apikeys.text:/apikeys.text
    command:
      - -hf-repo ggml-org/gemma-4-12B-it-GGUF \
      - -hf-file gemma-4-12B-it-Q4_0.gguf \
      - -alias gemma-4-12b-ha \
      - -host 0.0.0.0 \
      - -port 8080 \
      - -ctx-size 16384 \
      - -parallel 1 \
      - -n-gpu-layers 999 \
      - -flash-attn auto \
      - -reasoning off \
      - -cache-type-k q8_0 \
      - -cache-type-v q8_0 \
      - -jinja \
      - -api-key-file "/apikeys.text"