---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grocy-scanner
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: grocy-scanner
  values:
    controllers:
      grocy-scanner:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          grocy-scanner:
            image:
              repository: ghcr.io/manuel-rw/grocy-scanner
              tag: latest@sha256:fabcec961919ed6a27bea896e57a24e2cdbf7a45540ba234371b489d12a45a31
            env:
              Grocy__BaseUrl: http://grocy.default.svc.cluster.local
            envFrom:
              - secretRef:
                  name: grocy-secret
    route:
      grocy-scanner:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == any(200,401)"]
        hostnames:
          - "grocy-scanner.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: network
        rules:
          - backendRefs:
              - port: 80
                name: grocy-scanner
    service:
      grocy-scanner:
        controller: grocy-scanner
        type: ClusterIP
        ports:
          http:
            primary: true
            port: 80