---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./mcpgroup.yaml
  - ./truenas-external-auth.yaml
  - ./virtualmcpserver.yaml
  - ./externalsecret.yaml
  - ./httproute.yaml
  - ./securitypolicy.yaml
  - ./networkpolicy.yaml
  - ./proxy-runner-rbac.yaml
