---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: toolhive-servers
spec:
  dependsOn:
    - name: toolhive-operator
      namespace: mcp
  interval: 1h
  path: ./kubernetes/apps/mcp/toolhive-servers/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: mcp
  timeout: 5m
  wait: false
