# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: immich
  values:
    controllers:
      server:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.4.0@sha256:ebd9d30add17acdf935d73eb004758c7dfd9388aaa605fda70ad74378ab92aec
            envFrom:
              - secretRef:
                  name: immich-secret
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v2.7.5@sha256:c15bff75068effb03f4355997d03dc7e0fc58720c2b54ad6f7f10d1bc57efaa5
            env:
              REDIS_HOSTNAME: dragonfly.database.svc.cluster.local
              REDIS_PORT: 6379
              TZ: Europe/London
              PUBLIC_IMMICH_SERVER_URL: "https://photos.f9.casa"
            envFrom:
              - secretRef:
                  name: immich-secret
            resources:
              claims:
                - name: gpu
    defaultPodOptions:
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: immich-gpu
    service:
      server:
        controller: server
        ports:
          http:
            port: &port 2283
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == any(200,401)"]
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media Service
          gethomepage.dev/name: Immich
          gethomepage.dev/icon: immich
          gethomepage.dev/description: Photo Library
          gethomepage.dev/widget.type: immich
          gethomepage.dev/widget.url: http://immich.default:2283
          gethomepage.dev/widget.key: "{{ `{{HOMEPAGE_VAR_IMMICH_KEY}}` }}"
          gethomepage.dev/widget.version: "2"
        hostnames: ["photos.f9.casa"]
        parentRefs:
          - name: envoy-external
            namespace: network
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      matplotlib:
        type: emptyDir
        globalMounts:
          - path: /config/matplotlib
      library:
        type: nfs
        server: nas.main.internal
        path: /mnt/F9/Photos
        globalMounts:
          - path: /usr/src/app/upload
      tmpfs:
        type: emptyDir
        advancedMounts:
          server:
            main:
              - path: /usr/src/app/.reverse-geocoding-dump
                subPath: geocoding
              - path: /usr/src/app/.transformers_cache
                subPath: transformers