---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: kubernetes
spec:
  image: quay.io/containers/kubernetes_mcp_server:v0.0.67@sha256:e47f6ccc5347e1ea6be495d8d9ab55ac8a995fe87800fb984fa770cebe14ad44
  transport: streamable-http
  mcpPort: 8080
  serviceAccount: kubernetes-mcp-readonly
  groupRef:
    name: mcp-tools
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 256Mi
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          args:
            - --port
            - "8080"
            - --read-only
          env:
            - name: LOG_LEVEL
              value: "2"
