services:
  cups:
    container_name: "cups"
    devices:
      - "/dev/ricoh_printer:/dev/ricoh_printer"
    environment:
      TZ: "Europe/London"
      ADMIN_PASSWORD: "Password1"
    image: "ydkn/cups@sha256:02b949af550aef6a341aee472e191865f43611426fb1d9ea7d402e1e0c4ffeaf"
    network_mode: "bridge"
    ports:
      - "631:631/tcp"
    privileged: "true"
    restart: "unless-stopped"
    volumes:
      - "/mnt/apps-pool/appdata/cups:/etc/cups"
      - "/var/run/dbus:/var/run/dbus"
      - "/dev/bus/usb:/dev/bus/usb"
