services:
  cups:
    container_name: "cups"
    devices:
      - "/dev/ricoh_printer:/dev/ricoh_printer"
    environment:
      TZ: "Europe/London"
      ADMIN_PASSWORD: "Password1"
    image: "ydkn/cups@sha256:5c846646aacf2e30fd628282e09e536a1f6d363751bce50c52fb40ff371779ac"
    network_mode: "bridge"
    ports:
      - "631:631/tcp"
    privileged: "true"
    restart: "unless-stopped"
    volumes:
      - "/mnt/apps-pool/appdata/cups:/etc/cups"
      - "/var/run/dbus:/var/run/dbus"
      - "/dev/bus/usb:/dev/bus/usb"
