services:
  cups:
    container_name: "cups"
    devices:
      - "/dev/ricoh_printer:/dev/ricoh_printer"
    environment:
      TZ: "Europe/London"
      ADMIN_PASSWORD: "Password1"
    image: "ydkn/cups@sha256:a674219145cb9a153205d632cf5e1156b7aada4c1c189037b0a6b8a25043fea1"
    network_mode: "bridge"
    ports:
      - "631:631/tcp"
    privileged: "true"
    restart: "unless-stopped"
    volumes:
      - "/mnt/apps-pool/appdata/cups:/etc/cups"
      - "/var/run/dbus:/var/run/dbus"
      - "/dev/bus/usb:/dev/bus/usb"
